# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20171117_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
